# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detectedobject_pb2 as detectedobject__pb2
import trackedobject_pb2 as trackedobject__pb2


class DetectedObjectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendDetectedObject = channel.unary_unary(
                '/detectedobject.DetectedObjectService/SendDetectedObject',
                request_serializer=detectedobject__pb2.DetectedObjectMessage.SerializeToString,
                response_deserializer=trackedobject__pb2.TrackedObjectMessage.FromString,
                )


class DetectedObjectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendDetectedObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectedObjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendDetectedObject': grpc.unary_unary_rpc_method_handler(
                    servicer.SendDetectedObject,
                    request_deserializer=detectedobject__pb2.DetectedObjectMessage.FromString,
                    response_serializer=trackedobject__pb2.TrackedObjectMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'detectedobject.DetectedObjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DetectedObjectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendDetectedObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/detectedobject.DetectedObjectService/SendDetectedObject',
            detectedobject__pb2.DetectedObjectMessage.SerializeToString,
            trackedobject__pb2.TrackedObjectMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
