# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detectedobject.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import trackedobject_pb2 as trackedobject__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x65tectedobject.proto\x12\x0e\x64\x65tectedobject\x1a\x0c\x63ommon.proto\x1a\x13trackedobject.proto\"\xdf\x01\n\x15\x44\x65tectedObjectMessage\x12\x10\n\x08\x64\x65viceid\x18\x01 \x01(\t\x12\x0b\n\x03uid\x18\x02 \x01(\t\x12\x13\n\x0bscenemarkid\x18\x03 \x01(\t\x12\x32\n\x0c\x65ventoptions\x18\x04 \x01(\x0b\x32\x1c.detectedobject.EventOptions\x12\x12\n\nresolution\x18\x05 \x03(\x05\x12\"\n\x04\x61rea\x18\x06 \x03(\x0b\x32\x14.detectedobject.Area\x12&\n\x06object\x18\x07 \x03(\x0b\x32\x16.detectedobject.Object\"W\n\x04\x41rea\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\teventtype\x18\x02 \x01(\x0e\x32\x11.common.EventType\x12\x1d\n\x06points\x18\x03 \x03(\x0b\x32\r.common.Point\"\x8d\x01\n\x06Object\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x13\n\x0b\x66ramenumber\x18\x02 \x01(\x05\x12&\n\neventclass\x18\x03 \x01(\x0e\x32\x12.common.EventClass\x12\t\n\x01x\x18\x04 \x01(\x05\x12\t\n\x01y\x18\x05 \x01(\x05\x12\r\n\x05width\x18\x06 \x01(\x02\x12\x0e\n\x06height\x18\x07 \x01(\x02\"Q\n\x0c\x45ventOptions\x12*\n\x08tailgate\x18\x01 \x01(\x0b\x32\x18.detectedobject.TailGate\x12\x15\n\rloiteringTime\x18\x02 \x01(\x05\"\x18\n\x08TailGate\x12\x0c\n\x04time\x18\x01 \x01(\x01\x32{\n\x15\x44\x65tectedObjectService\x12\x62\n\x12SendDetectedObject\x12%.detectedobject.DetectedObjectMessage\x1a#.trackedobject.TrackedObjectMessage\"\x00\x42;\n\x1cio.grpc.nextk.detectedobjectB\x13\x44\x65tectedObjectProtoP\x01\xa2\x02\x03RFPb\x06proto3')



_DETECTEDOBJECTMESSAGE = DESCRIPTOR.message_types_by_name['DetectedObjectMessage']
_AREA = DESCRIPTOR.message_types_by_name['Area']
_OBJECT = DESCRIPTOR.message_types_by_name['Object']
_EVENTOPTIONS = DESCRIPTOR.message_types_by_name['EventOptions']
_TAILGATE = DESCRIPTOR.message_types_by_name['TailGate']
DetectedObjectMessage = _reflection.GeneratedProtocolMessageType('DetectedObjectMessage', (_message.Message,), {
  'DESCRIPTOR' : _DETECTEDOBJECTMESSAGE,
  '__module__' : 'detectedobject_pb2'
  # @@protoc_insertion_point(class_scope:detectedobject.DetectedObjectMessage)
  })
_sym_db.RegisterMessage(DetectedObjectMessage)

Area = _reflection.GeneratedProtocolMessageType('Area', (_message.Message,), {
  'DESCRIPTOR' : _AREA,
  '__module__' : 'detectedobject_pb2'
  # @@protoc_insertion_point(class_scope:detectedobject.Area)
  })
_sym_db.RegisterMessage(Area)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT,
  '__module__' : 'detectedobject_pb2'
  # @@protoc_insertion_point(class_scope:detectedobject.Object)
  })
_sym_db.RegisterMessage(Object)

EventOptions = _reflection.GeneratedProtocolMessageType('EventOptions', (_message.Message,), {
  'DESCRIPTOR' : _EVENTOPTIONS,
  '__module__' : 'detectedobject_pb2'
  # @@protoc_insertion_point(class_scope:detectedobject.EventOptions)
  })
_sym_db.RegisterMessage(EventOptions)

TailGate = _reflection.GeneratedProtocolMessageType('TailGate', (_message.Message,), {
  'DESCRIPTOR' : _TAILGATE,
  '__module__' : 'detectedobject_pb2'
  # @@protoc_insertion_point(class_scope:detectedobject.TailGate)
  })
_sym_db.RegisterMessage(TailGate)

_DETECTEDOBJECTSERVICE = DESCRIPTOR.services_by_name['DetectedObjectService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034io.grpc.nextk.detectedobjectB\023DetectedObjectProtoP\001\242\002\003RFP'
  _DETECTEDOBJECTMESSAGE._serialized_start=76
  _DETECTEDOBJECTMESSAGE._serialized_end=299
  _AREA._serialized_start=301
  _AREA._serialized_end=388
  _OBJECT._serialized_start=391
  _OBJECT._serialized_end=532
  _EVENTOPTIONS._serialized_start=534
  _EVENTOPTIONS._serialized_end=615
  _TAILGATE._serialized_start=617
  _TAILGATE._serialized_end=641
  _DETECTEDOBJECTSERVICE._serialized_start=643
  _DETECTEDOBJECTSERVICE._serialized_end=766
# @@protoc_insertion_point(module_scope)
