# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trackedobject.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13trackedobject.proto\x12\rtrackedobject\x1a\x0c\x63ommon.proto\"[\n\x14TrackedObjectMessage\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12(\n\teventinfo\x18\x02 \x03(\x0b\x32\x15.trackedobject.Object\x12\x0c\n\x04time\x18\x03 \x01(\x03\"\xa2\x01\n\x06Object\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x66ramenumber\x18\x02 \x01(\x05\x12$\n\teventtype\x18\x03 \x01(\x0e\x32\x11.common.EventType\x12&\n\neventclass\x18\x04 \x01(\x0e\x32\x12.common.EventClass\x12\x0b\n\x03\x62ox\x18\x05 \x03(\x05\x12\x0e\n\x06zoneid\x18\x06 \x01(\x05\x12\x0c\n\x04time\x18\x07 \x01(\x03\x42\x39\n\x1bio.grpc.nextk.trackedobjectB\x12TrackedobjectProtoP\x01\xa2\x02\x03RFPb\x06proto3')



_TRACKEDOBJECTMESSAGE = DESCRIPTOR.message_types_by_name['TrackedObjectMessage']
_OBJECT = DESCRIPTOR.message_types_by_name['Object']
TrackedObjectMessage = _reflection.GeneratedProtocolMessageType('TrackedObjectMessage', (_message.Message,), {
  'DESCRIPTOR' : _TRACKEDOBJECTMESSAGE,
  '__module__' : 'trackedobject_pb2'
  # @@protoc_insertion_point(class_scope:trackedobject.TrackedObjectMessage)
  })
_sym_db.RegisterMessage(TrackedObjectMessage)

Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
  'DESCRIPTOR' : _OBJECT,
  '__module__' : 'trackedobject_pb2'
  # @@protoc_insertion_point(class_scope:trackedobject.Object)
  })
_sym_db.RegisterMessage(Object)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.nextk.trackedobjectB\022TrackedobjectProtoP\001\242\002\003RFP'
  _TRACKEDOBJECTMESSAGE._serialized_start=52
  _TRACKEDOBJECTMESSAGE._serialized_end=143
  _OBJECT._serialized_start=146
  _OBJECT._serialized_end=308
# @@protoc_insertion_point(module_scope)
